// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    var templateEscape;
    templateEscape = function(str) {
      str = str.replace(/&lt;/g, "<");
      return str = str.replace(/&gt;/g, ">");
    };
    return App.Employees = {
      baseUrl: 'http://mo.aitormurray.com/',
      initialize: function() {
        var Employee, EmployeeList, EmployeeListView, EmployeeView, employeeList, employeeListView;
        Employee = Backbone.Model.extend({
          urlRoot: "" + App.Employees.baseUrl + "/API/employees",
          defaults: ''
        });
        EmployeeView = Backbone.View.extend({
          tagName: 'article',
          className: 'employee',
          template: _.template(templateEscape($('#template').html())),
          render: function() {
            this.$el.html(this.template(this.model.toJSON()));
            this.$el.find('.picture img').attr('src', "" + App.Employees.baseUrl + "img/employees/" + this.model.attributes.picture);
            this.$el.find('.gender img').attr('src', "img/" + this.model.attributes.gender + "-gender-sign.jpg");
            return this;
          }
        });
        EmployeeList = Backbone.Collection.extend({
          model: Employee,
          url: "" + App.Employees.baseUrl + "/API/employees"
        });
        EmployeeListView = Backbone.View.extend({
          initialize: function() {
            this.collection.on('add', this.addOne, this);
            return this.collection.on('reset', this.addAll, this);
          },
          addOne: function(model) {
            var View;
            View = new EmployeeView({
              model: model
            });
            View.render();
            return this.$el.append(View.el);
          },
          addAll: function() {
            this.collection.forEach(this.addOne, this);
            return $(document).trigger('showList');
          },
          render: function() {
            return this.addAll();
          }
        });
        employeeList = new EmployeeList();
        employeeListView = new EmployeeListView({
          collection: employeeList
        });
        $(document).on('showList', function() {
          $('#container').animate({
            opacity: 1
          }, 500);
          return $('.loading').hide();
        });
        employeeList.fetch({
          reset: true,
          success: function(e) {
            return console.log(e);
          },
          error: function(e) {
            console.log(e);
            return $('#container').append("Error de conexion");
          }
        });
        return $('#container').append(employeeListView.el);
      }
    };
  });

}).call(this);
